// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { SearchData, SearchError, SearchResponse, GetPersonData, GetPersonError, GetPersonResponse, UpdatePersonData, UpdatePersonError, UpdatePersonResponse, DeletePersonData, DeletePersonError, DeletePersonResponse, CreatePersonData, CreatePersonError, CreatePersonResponse, GetSuggestionsData, GetSuggestionsError, GetSuggestionsResponse, GetRecentSearchesError, GetRecentSearchesResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Search
 */
export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>) => { return (options?.client ?? client).post<SearchResponse, SearchError, ThrowOnError>({
    ...options,
    url: '/api/search'
}); };

/**
 * Get Person
 */
export const getPerson = <ThrowOnError extends boolean = false>(options: Options<GetPersonData, ThrowOnError>) => { return (options?.client ?? client).get<GetPersonResponse, GetPersonError, ThrowOnError>({
    ...options,
    url: '/api/person/{person_id}'
}); };

/**
 * Update Person
 */
export const updatePerson = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonData, ThrowOnError>) => { return (options?.client ?? client).put<UpdatePersonResponse, UpdatePersonError, ThrowOnError>({
    ...options,
    url: '/api/person/{person_id}'
}); };

/**
 * Delete Person
 */
export const deletePerson = <ThrowOnError extends boolean = false>(options: Options<DeletePersonData, ThrowOnError>) => { return (options?.client ?? client).delete<DeletePersonResponse, DeletePersonError, ThrowOnError>({
    ...options,
    url: '/api/person/{person_id}'
}); };

/**
 * Create Person
 */
export const createPerson = <ThrowOnError extends boolean = false>(options: Options<CreatePersonData, ThrowOnError>) => { return (options?.client ?? client).post<CreatePersonResponse, CreatePersonError, ThrowOnError>({
    ...options,
    url: '/api/person'
}); };

/**
 * Get Suggestions
 */
export const getSuggestions = <ThrowOnError extends boolean = false>(options: Options<GetSuggestionsData, ThrowOnError>) => { return (options?.client ?? client).get<GetSuggestionsResponse, GetSuggestionsError, ThrowOnError>({
    ...options,
    url: '/api/suggestions'
}); };

/**
 * Get Recent Searches
 */
export const getRecentSearches = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetRecentSearchesResponse, GetRecentSearchesError, ThrowOnError>({
    ...options,
    url: '/api/recent-searches'
}); };