// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Person = {
    name: string;
    email: string;
    profession: string;
    location: string;
    skills: Array<(string)>;
    years_of_experience?: (number | null);
    education?: (string | null);
    bio?: (string | null);
    linkedin_profile?: (string | null);
    website?: (string | null);
    availability?: (string | null);
    hourly_rate?: (number | null);
    last_active?: (string | null);
    id?: (number | null);
    created_at?: string;
    updated_at?: string;
};

export type SearchQuery = {
    query: string;
};

export type SearchResult = {
    results: Array<Person>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SearchData = {
    body: SearchQuery;
};

export type SearchResponse = (SearchResult);

export type SearchError = (HTTPValidationError);

export type GetPersonData = {
    path: {
        person_id: number;
    };
};

export type GetPersonResponse = (Person);

export type GetPersonError = (HTTPValidationError);

export type UpdatePersonData = {
    body: Person;
    path: {
        person_id: number;
    };
};

export type UpdatePersonResponse = (Person);

export type UpdatePersonError = (HTTPValidationError);

export type DeletePersonData = {
    path: {
        person_id: number;
    };
};

export type DeletePersonResponse = (unknown);

export type DeletePersonError = (HTTPValidationError);

export type CreatePersonData = {
    body: Person;
};

export type CreatePersonResponse = (Person);

export type CreatePersonError = (HTTPValidationError);

export type GetSuggestionsData = {
    query: {
        partial_query: string;
    };
};

export type GetSuggestionsResponse = (unknown);

export type GetSuggestionsError = (HTTPValidationError);

export type GetRecentSearchesResponse = (unknown);

export type GetRecentSearchesError = unknown;